# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'content.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pkg.handlers.paths import resource_path


class Ui_spa_app(object):
    @staticmethod
    def __image_path_builder(image_name):
        return resource_path("assets", "images", image_name)

    def setupUi(self, spa_app):
        spa_app.setObjectName("spa_app")
        spa_app.resize(1060, 800)
        self.content_window = QtWidgets.QWidget(spa_app)
        self.content_window.setObjectName("content_window")
        self.gridLayout = QtWidgets.QGridLayout(self.content_window)
        self.gridLayout.setObjectName("gridLayout")
        self.pages_group = QtWidgets.QWidget(self.content_window)
        self.pages_group.setStyleSheet(
            "QWidget {\n"
            "    background: #2b2e4a ;\n"
            "    border: none;\n"
            "    color: white;\n"
            "    font-size: 20px;\n"
            "    font-weight: 900;\n"
            "}"
        )
        self.pages_group.setObjectName("pages_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pages_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home_page = QtWidgets.QPushButton(self.pages_group)
        self.home_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_page.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.home_page.setObjectName("home_page")
        self.horizontalLayout.addWidget(self.home_page)
        self.geometry_page = QtWidgets.QPushButton(self.pages_group)
        self.geometry_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.geometry_page.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.geometry_page.setObjectName("geometry_page")
        self.horizontalLayout.addWidget(self.geometry_page)
        self.matrix_page = QtWidgets.QPushButton(self.pages_group)
        self.matrix_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.matrix_page.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.matrix_page.setObjectName("matrix_page")
        self.horizontalLayout.addWidget(self.matrix_page)
        self.gridLayout.addWidget(self.pages_group, 0, 0, 1, 2)
        self.theme_section = QtWidgets.QTreeView(self.content_window)
        self.theme_section.setMaximumSize(QtCore.QSize(260, 16777215))
        self.theme_section.setStyleSheet(
            "QTreeView {\n"
            "    background: #2b2e4a ;\n"
            "    border: none;\n"
            "    color: white;\n"
            "    font-size: 20px;\n"
            "}"
            "\n"
            "QTreeView::item {\n"
            "   padding: 10px;\n"
            "}"
            "\n"
            "QTreeView::item:hover {\n"
            "   background: #903749;\n"
            "}"
        )
        self.theme_section.setAlternatingRowColors(False)
        self.theme_section.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.theme_section.setObjectName("theme_section")
        self.theme_section.setHeaderHidden(True)
        self.gridLayout.addWidget(self.theme_section, 1, 0, 1, 1)
        self.content_frame = QtWidgets.QWidget(self.content_window)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.theme_options = QtWidgets.QWidget(self.content_frame)
        self.theme_options.setStyleSheet(
            "QWidget {\n"
            "    background: #2b2e4a ;\n"
            "    border: none;\n"
            "    padding: 10px;\n"
            "    color: white;\n"
            "    font-size: 14px;\n"
            "    font-weight: bold;\n"
            "}"
        )
        self.theme_options.setObjectName("theme_options")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.theme_options)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.theory_btn = QtWidgets.QPushButton(self.theme_options)
        self.theory_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theory_btn.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.theory_btn.setObjectName("theory_btn")
        self.horizontalLayout_2.addWidget(self.theory_btn)
        self.second_exmple_btn = QtWidgets.QPushButton(self.theme_options)
        self.second_exmple_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.second_exmple_btn.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.second_exmple_btn.setObjectName("second_exmple_btn")
        self.horizontalLayout_2.addWidget(self.second_exmple_btn)
        self.first_example_btn = QtWidgets.QPushButton(self.theme_options)
        self.first_example_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.first_example_btn.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.first_example_btn.setObjectName("first_example_btn")
        self.horizontalLayout_2.addWidget(self.first_example_btn)
        self.practice_btn = QtWidgets.QPushButton(self.theme_options)
        self.practice_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.practice_btn.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #903749;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #e84545;\n"
            "}"
        )
        self.practice_btn.setObjectName("practice_btn")
        self.horizontalLayout_2.addWidget(self.practice_btn)
        self.gridLayout_2.addWidget(self.theme_options, 0, 0, 1, 1)
        self.content_scroll_area = QtWidgets.QScrollArea(self.content_frame)
        self.content_scroll_area.setWidgetResizable(True)
        self.content_scroll_area.setObjectName("content_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 753, 664))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.content_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.layout_SArea = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.content_scroll_area, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.content_frame, 1, 1, 1, 1)
        spa_app.setCentralWidget(self.content_window)

        self.retranslateUi(spa_app)
        QtCore.QMetaObject.connectSlotsByName(spa_app)

    def retranslateUi(self, spa_app):
        _translate = QtCore.QCoreApplication.translate
        spa_app.setWindowTitle(
            _translate(
                "spa_app",
                "Интерактивный обучающий курс по изучению математики с использованием языка Python",
            )
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(self.__image_path_builder("icon.png")),
            QtGui.QIcon.Selected,
            QtGui.QIcon.On,
        )
        spa_app.setWindowIcon(icon)
        self.home_page.setText(_translate("spa_app", "Главная"))
        self.geometry_page.setText(_translate("spa_app", "Геометрия"))
        self.matrix_page.setText(_translate("spa_app", "Матрицы"))
        self.theory_btn.setText(_translate("spa_app", "Теория"))
        self.second_exmple_btn.setText(_translate("spa_app", "Пример 1"))
        self.first_example_btn.setText(_translate("spa_app", "Пример 2"))
        self.practice_btn.setText(_translate("spa_app", "Практика"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    spa_app = QtWidgets.QMainWindow()
    ui = Ui_spa_app()
    ui.setupUi(spa_app)
    spa_app.show()
    sys.exit(app.exec_())
