# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pkg.handlers.paths import resource_path


class Ui_MainWindow(object):
    @staticmethod
    def __image_path_builder(image_name):
        return resource_path("assets", "images", image_name)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 700)
        MainWindow.setStyleSheet("background: #2b2e4a;\n" "\n" "")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(self.__image_path_builder("icon.png")),
            QtGui.QIcon.Selected,
            QtGui.QIcon.On,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.presentation = QtWidgets.QTextEdit(self.centralwidget)
        self.presentation.setEnabled(True)
        self.presentation.setAutoFillBackground(False)
        self.presentation.setStyleSheet(
            "QTextEdit {\n"
            "    background: #eee;\n"
            "    border: none;\n"
            "    color: black;\n"
            "    font-size: 16px;\n"
            "}"
        )
        self.presentation.setReadOnly(True)
        self.presentation.setOverwriteMode(False)
        self.presentation.setObjectName("presentation")
        self.gridLayout.addWidget(self.presentation, 2, 0, 1, 1)
        self.logo_polytech = QtWidgets.QLabel(self.centralwidget)
        image_path = self.__image_path_builder("mospolytech.png")
        q_pixmap = QtGui.QPixmap(image_path)
        self.logo_polytech.setPixmap(q_pixmap)
        self.logo_polytech.setMinimumSize(QtCore.QSize(0, 200))
        self.logo_polytech.setMaximumSize(QtCore.QSize(16777215, 200))
        self.logo_polytech.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_polytech.setObjectName("logo_polytech")
        self.gridLayout.addWidget(self.logo_polytech, 0, 0, 1, 1)
        self.prev = QtWidgets.QPushButton(self.centralwidget)
        self.prev.setEnabled(True)
        self.prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prev.setStyleSheet(
            "QPushButton {\n"
            "    border: none; \n"
            "    color: white;\n"
            "    font-size: 14px;\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    border-radius: 4px;\n"
            "    color: #2b2e4a;\n"
            "    background: white;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-radius: 4px;\n"
            "    color: white;\n"
            "    background: #2b2e4a;\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.prev.setFlat(False)
        self.prev.setObjectName("prev")
        self.gridLayout.addWidget(self.prev, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главная"))
        self.presentation.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n ul, ol, p {font-size: 16px;}"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                '<h1 style=" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt; font-weight:600;"> Интерактивный курс по изучению математики и основ программирования с использованием языка Python </span></h1>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt; font-weight:600;"> О курсе </span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt;">Здесь вы сможете познакомиться со способами решения математических задач при помощи Python.</span></p>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;"><span style=" font-size:8pt; font-weight:600;">Автор:</span></h4>\n'
                '<ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li style=" font-size:8pt;" style=" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Панасенко Елена Викторовна</li>\n'
                '<li style=" font-size:8pt;" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Группа: 171-334</li>\n'
                '<li style=" font-size:8pt;" style=" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Год выпуска: 2021</li></ul>\n'
                '<h4 style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;"><span style=" font-size:8pt; font-weight:600;">Для достижения максимальной пользы при прохождении тем разделов курса необходимо:</span></h4>\n'
                '<ol style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li style=" font-size:8pt;" style=" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Установить PyCharm или любую другую удобную среду разработки для работы с Python.</li>\n'
                '<li style=" font-size:8pt;" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Установить интерпретатор языка Python версии 3.8.5.</li>\n'
                '<li style=" font-size:8pt;" style=" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Следовать инструкциям, описанным в практических заданиях.</li></ol>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.prev.setText(_translate("MainWindow", "Приступить к обучению"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
